namespace: linux
name: kernel
description: The Linux kernel
homepage_url: https://www.kernel.org/
vcs_url: https://git.kernel.org/
download_url: https://www.kernel.org/pub/
license: GPL-2.0-only WITH Linux-syscall-notes
contact:
    - type: person
      name: Greg Kroah-Hartman
      role: maintainer
      email: greg@example.com

alternative_purls:
    - pkg:github/torvalds/linux
    - pkg:github/gregkh/linux
